import React from 'react';
import type { Metadata } from 'next';
import {
  AppShell,
  AppShellMain,
  AppShellNavbar,
} from '@mantine/core';
import { NavigationBar } from '@/components/NavigationBar/NavigationBar';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppShell
          navbar={{
            width: '280px',
            breakpoint: 'sm',
          }}
        >
          <AppShellNavbar
            className='nav-bar'
            withBorder={false}
          >
            <NavigationBar />
          </AppShellNavbar>
          <AppShellMain>
            {children}
          </AppShellMain>
        </AppShell>
      </body>
    </html>
  );
}
