import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ColorSchemeScript, Flex, MantineProvider } from '@mantine/core';
import { NavigationBar } from '@/components/NavigationBar/NavigationBar';
import StoreProvider from '@/app/StoreProvider';
import '@mantine/core/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript/>
      </head>
      <body className={inter.className}>
        <StoreProvider>
          <MantineProvider>
            <Flex>
              <NavigationBar />
              {children}
            </Flex>
          </MantineProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
